spring:
  profiles:
    include: dev-eureka,dev-logback
  zipkin:
    base-url: http://localhost:9411
  #spring.sleuth.sampler.probalility指定采样百分比，默认0.1，改成1.0表示所有数据都采用
  sleuth:
    sampler:
      probability: 1.0

